name: learning_about_b4a_dart_speed
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  parse_server_sdk: ^4.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
